/*   Automatically generated by Iup 3 LED Compiler to C.   */

#include <stdlib.h>
#include <stdarg.h>
#include <iup.h>

static Ihandle* named[      9 ];

#include <iupcontrols.h>
#include <iup_scintilla.h>

void led_load (void)
{
  named[0] = IupSetAtt( "mnu_main", IupMenu(
    IupSubmenu( "File",
      IupMenu(
        IupItem( "In-&memory Database\tCtrl+N", "cb_file_new" ),
        IupItem( "Database &File...\tCtrl+O", "cb_file_open" ),
        IupSeparator(),
        IupItem( "&Attach...", "cb_file_attach" ),
        IupItem( "&Detach...", "cb_file_detach" ),
        IupSeparator(),
        IupItem( "E&xit", "cb_default_close" ),
      NULL)
    ),
    IupSubmenu( "Edit",
      IupMenu(
        IupSubmenu( "&Create",
          IupMenu(
            IupItem( "&Table...", "cb_edit_create_table" ),
            IupItem( "&Index...", "cb_edit_create_index" ),
            IupItem( "&View...", "cb_edit_create_view" ),
            IupItem( "Tri&gger...", "cb_edit_create_trigger" ),
          NULL)
        ),
        IupItem( "&Drop...", "cb_edit_drop" ),
        IupSeparator(),
        IupSubmenu( "&Transaction",
          IupMenu(
            IupItem( "&Begin\tCtrl+B", "cb_edit_transaction_begin" ),
            IupItem( "&Commit\tCtrl+M", "cb_edit_transaction_commit" ),
            IupItem( "&Rollback\tCtrl+R", "cb_edit_transaction_rollback" ),
          NULL)
        ),
        IupSeparator(),
        IupSubmenu( "&Import",
          IupMenu(
            IupItem( "From &SQL...", "cb_file_import_sql" ),
            IupItem( "From CS&V...", "cb_file_import_csv" ),
          NULL)
        ),
        IupItem( "&Export...", "cb_file_export" ),
        IupSeparator(),
        IupItem( "&Pragmas...", "cb_edit_pragmas" ),
      NULL)
    ),
    IupSubmenu( "Help",
      IupMenu(
        IupItem( "&About...", "cb_help_about" ),
      NULL)
    ),
  NULL), NULL );
  named[1] = IupSetAtt( "ctl_toolbar", IupHbox(
    IupButton( "&Open", "cb_file_open" ),
    IupButton( "New &Table", "cb_edit_create_table" ),
  NULL), NULL );
  named[2] = IupSetAtt( "dlg_main", IupDialog(
    IupVbox(
      named[1] /* ctl_toolbar */,
      IupSetAtt( NULL, IupSplit(
        named[3] = IupSetAtt( "ctl_tree", IupTree(), 
          "TITLE0", "Databases", 
          "SIZE", "100x", NULL ),
        IupSetAtt( NULL, IupSplit(
          named[4] = IupSetAtt( "ctl_matrix", IupMatrix( "cb_matrix" ), 
            "NAME", "MATVIEW", 
            "SIZE", "300x150", 
            "RESIZEMATRIX", "YES", 
            "EDITFITVALUE", "YES", 
            "MULTILINE", "YES", NULL ),
          IupSetAtt( NULL, IupFrame(
            IupHbox(
              named[5] = IupSetAtt( "ctl_cmdline", IupScintilla(), 
                "EXPAND", "YES", 
                "LEXERLANGUAGE", "sql", 
                "SIZE", "100x50", NULL ),
              IupVbox(
                IupFill(),
                IupSetAtt( NULL, IupButton( "E&xecute", "cb_execute" ), 
                  "EXPAND", "NO", NULL ),
              NULL),
            NULL)
          ), 
            "TITLE", "SQL", NULL )
        ), 
          "ORIENTATION", "HORIZONTAL", NULL )
      ), 
        "ORIENTATION", "VERTICAL", NULL ),
    NULL)
  ), 
    "TITLE", "Yet Another SQLite Frontend", 
    "SHRINK", "YES", 
    "MENU", "mnu_main", 
    "MAP_CB", "cb_main_init", NULL );
  named[6] = IupSetAtt( "dlg_about", IupMessageDlg(), 
    "DIALOGTYPE", "INFORMATION", 
    "TITLE", "About", NULL );
  named[7] = IupSetAtt( "dlg_open", IupFileDlg(), 
    "ALLOWNEW", "YES", 
    "EXTFILTER", "SQLite database (*.db;*.sqlite)|*.db;*.sqlite|All files (*.*)|*.*", NULL );
}
