#!/usr/bin/env lua

local protos = {}
for _, f in ipairs(arg) do
  for line in io.lines(f) do
    local name = line:match "^int (cb_[%w_]+)%b()$"
    if name then
      protos[name] = line
    end
  end
end

local c = io.open('regcb.c', 'w')
local h = io.open('regcb.h', 'w')

c:write("/* Generated by regcb.lua. DO NOT EDIT! */\n")
h:write("/* Generated by regcb.lua. DO NOT EDIT! */\n")

for name, proto in pairs(protos) do
  h:write(('extern %s;\n'):format(proto))
  c:write(('IupSetFunction("%s", (Icallback) &%s);\n'):format(name, name))
end

-- vim: ts=2:sw=2:et
